name: Grab EPG
on: [push]
jobs:
  grab_epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout epg repository
        uses: actions/checkout@v2
        with:
          repository: iptv-org/epg
          ref: master

      - name: Install dependencies
        run: |
          cd epg
          npm install

      - name: Grab EPG from site 1
        run: |
          cd epg
          SITE=superguidatv.it npm run grab

      - name: Grab EPG from site 2
        run: |
          cd epg
          SITE=tvguide.com npm run grab

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Grab EPG updates'
